# Generated by Django 4.2.3 on 2023-07-28 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0007_remove_ticker_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
