# Generated by Django 4.2.3 on 2023-08-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0011_alter_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.CharField(blank=True, null=True),
        ),
    ]
