# Generated by Django 4.2.3 on 2023-08-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0013_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
