# Generated by Django 4.2.3 on 2023-08-10 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0015_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1)),
        ),
    ]
