# Generated by Django 4.2.3 on 2023-08-10 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0016_alter_transaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='trade_direction',
        ),
    ]
